name: "Run performance tests"
on:
  push:
    branches: [main]
  pull_request:
    branches: ['**']

jobs:
  main:
    name: Run performance tests
    runs-on: ubuntu-latest
    steps:
      - name: Run Reassure
        run: ./reassure-tests.sh

      - name: Run Danger.js
        run: yarn danger ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}